apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Gnauk841026/demo_simple_website.git'
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
